# Generated by Django 3.2.6 on 2021-09-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210909_0246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name']},
        ),
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.ManyToManyField(blank=True, to='members.Address'),
        ),
    ]
