# Generated by Django 3.2.6 on 2021-09-09 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_board_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='member',
        ),
        migrations.AddField(
            model_name='person',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='members.membership'),
        ),
    ]
