# Generated by Django 3.2.6 on 2021-09-09 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20210909_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='membership',
        ),
        migrations.AddField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='members.person'),
        ),
    ]
