# Generated by Django 3.2.6 on 2021-09-09 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20210909_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='member',
        ),
        migrations.AddField(
            model_name='membership',
            name='description',
            field=models.CharField(default='hi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='members.membership'),
        ),
    ]
