# Generated by Django 3.2.6 on 2021-09-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_needsreview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='needsreview',
            name='summary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='needsreview',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
