# Generated by Django 3.2.6 on 2021-09-09 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20210909_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needsreview',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='members.person'),
        ),
    ]
