# Generated by Django 3.2.6 on 2021-09-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_alter_needsreview_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needsreview',
            name='reason',
            field=models.CharField(choices=[('Name', 'Name'), ('Address', 'Address'), ('Email', 'Email'), ('Phone Number', 'Phone Number'), ('Partner', 'Partner'), ('Council Membership', 'Council Membership'), ('Board Membership', 'Board Membership'), ('Committee Membeship', 'Committee Membeship')], max_length=30),
        ),
    ]
