# Generated by Django 3.2.6 on 2021-09-09 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_needsreview_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needsreview',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='members.board'),
        ),
    ]
