# Generated by Django 3.2.6 on 2021-09-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_alter_needsreview_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needsreview',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
