# Generated by Django 3.2.6 on 2021-09-10 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_alter_needsreview_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['person']},
        ),
        migrations.RemoveField(
            model_name='committee',
            name='person',
        ),
        migrations.AddField(
            model_name='committee',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmte_member', to='members.person'),
        ),
    ]
