# Generated by Django 3.2.6 on 2021-09-10 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_alter_committee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['brd_member']},
        ),
        migrations.AlterModelOptions(
            name='committee',
            options={'ordering': ['cmte_member']},
        ),
        migrations.RenameField(
            model_name='committee',
            old_name='person',
            new_name='cmte_member',
        ),
        migrations.RemoveField(
            model_name='board',
            name='person',
        ),
        migrations.AddField(
            model_name='board',
            name='brd_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brd_member', to='members.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='board_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='so', to='members.person'),
        ),
    ]
