# Generated by Django 3.2.6 on 2021-09-10 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_auto_20210910_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='committee',
            options={'ordering': ['role']},
        ),
        migrations.RemoveField(
            model_name='person',
            name='board_member',
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Past President', 'Past President'), ('Commitee', 'Commitee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='committee',
            name='cmte_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmte_member', to='members.board'),
        ),
    ]
