# Generated by Django 3.2.6 on 2021-09-11 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20210910_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='brd_member',
            new_name='board_member',
        ),
    ]
