# Generated by Django 3.2.6 on 2021-09-11 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_auto_20210911_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='person1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member1', to='members.person'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='person2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='members.person'),
        ),
    ]
