# Generated by Django 3.2.6 on 2021-09-11 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_auto_20210911_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='person1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership1', related_query_name='membership', to='members.person'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='person2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership2', related_query_name='membership', to='members.person'),
        ),
    ]
