# Generated by Django 3.2.6 on 2021-09-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_auto_20210911_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='notes',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
