# Generated by Django 3.2.6 on 2021-09-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_auto_20210911_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
