# Generated by Django 3.2.6 on 2021-09-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_person_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
