# Generated by Django 3.2.6 on 2021-09-11 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0035_auto_20210911_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board_member',
            new_name='person',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='cmte_member',
        ),
        migrations.AddField(
            model_name='board',
            name='committee',
            field=models.ManyToManyField(to='members.Committee'),
        ),
        migrations.AddField(
            model_name='committee',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmte_member', to='members.person'),
        ),
    ]
