# Generated by Django 3.2.6 on 2021-09-11 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0036_auto_20210911_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='committee',
        ),
    ]
