# Generated by Django 3.2.6 on 2021-09-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_alter_board_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='role',
            new_name='committees',
        ),
    ]
