# Generated by Django 3.2.6 on 2021-09-11 20:42

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0040_rename_role_board_committees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='committees',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ADVISORY', 'Advisory'), ('ARCHIVES', 'Archives'), ('BOOK_CLUB', 'Book Club'), ('COMMUNICATION', 'Communications'), ('DAY_TRIPS', 'Day Trips'), ('MEMBERSHIPS', 'Memberships'), ('MEMBERSHIP_DEV', 'Membership Development'), ('DIRECTORY', 'Directory'), ('PHOTOGRAPHER', 'Photographer'), ('PROGRAMS', 'Programs'), ('SPECIAL_EVENTS', 'Special Events'), ('HOSPITALITY', [('Hopitality: Beverages', 'Beverages'), ('Hopitality: Food', 'Food'), ('Hopitality: Greeter', 'Greeter'), ('Hopitality: RSVP and Name Tags', 'RSVPs/Name Tags')]), ('TRAVEL', 'Travel'), ('BOT_COUNCIL_LIAISON', 'Board of Trustees Council Liaison'), ('COUNCIL_COORDINATOR', 'Council Coordinator')], max_length=40),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(choices=[('PRESIDENT', 'President'), ('VICE_PRESIDENT', 'Vice President'), ('SECRETARY', 'Secretary'), ('TREASURER', 'Treasurer'), ('PAST_PRESIDENT', 'Past President'), ('COMMITTEE', 'Commitee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='level',
            field=models.CharField(choices=[('SUPPORTER', 'Supporter'), ('CONTRIBUTOR', 'Contributor'), ('ADVOCATE', 'Advocate'), ('HONORARY', 'Honorary'), ('PAM_STAFF', 'PAM staff')], default='SUPPORTER', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='needsreview',
            name='component',
            field=models.CharField(choices=[('NAME', 'Name'), ('ADDRESS', 'Address'), ('EMAIL', 'Email'), ('PHONE_NUMBER', 'Phone Number'), ('PARTNER', 'Partner'), ('MEMBERSHIP', 'Council Membership'), ('BOARD', 'Board Membership'), ('COMMITTEE', 'Committee Membeship')], max_length=30),
        ),
        migrations.AlterField(
            model_name='needsreview',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
