# Generated by Django 3.2.6 on 2021-09-11 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0043_auto_20210911_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='person',
            new_name='person1',
        ),
    ]
