# Generated by Django 3.2.6 on 2021-09-11 21:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0046_alter_board_committees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='committees',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Advisory', 'Advisory'), ('Archives', 'Archives'), ('Book Club', 'Book Club'), ('Communication', 'Communications'), ('Day Trips', 'Day Trips'), ('Memberships', 'Memberships'), ('Membership Development', 'Membership Development'), ('Directory', 'Directory'), ('Photographer', 'Photographer'), ('Programs', 'Programs'), ('Special Events', 'Special Events'), ('Hopitality: Beverages', 'Hopitality: Beverages'), ('Hopitality: Food', 'Hopitality: Food'), ('Hopitality: Greeter', 'Hopitality: Greeter'), ('Hopitality: RSVPs/Name Tags', 'Hopitality: RSVPs/Name Tags'), ('Travel', 'Travel'), ('Board of Trustees Council Liaison', 'Board of Trustees Council Liaison'), ('Council Coordinator', 'Council Coordinator')], max_length=50),
        ),
    ]
