# Generated by Django 3.2.6 on 2021-09-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0047_alter_board_committees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='person1',
            new_name='board_member',
        ),
    ]
