# Generated by Django 3.2.6 on 2021-09-11 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0048_rename_person1_board_board_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board_member',
            new_name='person1',
        ),
    ]
