# Generated by Django 3.2.6 on 2021-09-11 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0049_rename_board_member_board_person1'),
    ]

    operations = [
        migrations.AddField(
            model_name='needsreview',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nr_member', to='members.person'),
        ),
        migrations.AddField(
            model_name='needsreview',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nr_person', to='members.person'),
        ),
    ]
