# Generated by Django 3.2.6 on 2021-09-11 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0050_auto_20210911_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needsreview',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nr_member', to='members.membership'),
        ),
    ]
