# Generated by Django 3.2.6 on 2021-09-12 02:13

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0052_remove_membership_needs_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='expiration',
            field=models.DateField(blank=True, default=members.models.one_year_from_today, null=True),
        ),
    ]
