# Generated by Django 3.2.6 on 2021-09-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0053_alter_membership_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='level',
            field=models.CharField(choices=[('Supporter', 'Supporter'), ('Contributor', 'Contributor'), ('Advocate', 'Advocate'), ('Honorary', 'Honorary'), ('PAM staff', 'PAM staff')], default='Supporter', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
