# Generated by Django 3.2.6 on 2021-09-12 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0054_auto_20210912_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='person2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='so', to='members.person', to_field='partner'),
        ),
        migrations.AlterField(
            model_name='person',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='members.person', unique=True),
        ),
    ]
