# Generated by Django 3.2.6 on 2021-09-12 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0055_auto_20210912_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='partner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='members.person'),
        ),
    ]
